# -*- coding: utf-8 -*-
"""CHESS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19sCsas8ONmSeyMKV19rQmtkC_sPzE48Q
"""

checkerboard =[

[1, 0, 0, 0, 0, 0, 0, 0],

[0, 0, 0, 0, 0, 0, 0, 0],

[0, 0, 0, 0, 0, 0, 0, 0],

[0, 0, 0, 0, 0, 0, 0, 0],

[0, 0, 0, 0, 0, 0, 0, 0],

[0, 0, 0, 0, 0, 0, 0, 0],

[0, 0, 0, 0, 0, 0, 0, 0],

[0, 0, 0, 0, 0, 0, 0, 0]

]
print(checkerboard[0][0])

checkerboard=[
  [1, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 1, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0] ]

position1=input().split()
position2=input().split()
x1,y1=int(position1[0]),int(position1[1])
x2,y2=int(position2[0]),int(position2[1])

if x1==x2 and y1==y2:
  print("No")
elif checkerboard[x2][y2]==1:
  print("No")
else
  if abs(x1-x2)<=1 and abs(y1-y2)<=1:
    print("Yes")
  else:
    print("No")

print(position1)
print(position2)
print(x1,y1,x2,y2)

checkerboard=[
  [1, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 1, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0] ]

position1=input().split()
position2=input().split()
x1,y1=int(position1[0]),int(position1[1])
x2,y2=int(position2[0]),int(position2[1])

if x1==x2 and y1==y2:
  print("No")
elif checkerboard[x2][y2]==1:
  print("No")
else:
  if abs(x1-x2)<=1 and abs(y1-y2)<=1:
    print("Yes")
  else:
    print("No")

position1=input().split()
position2=input().split()
x1,y1=int(position1[0]),int(position1[1])
x2,y2=int(position2[0]),int(position2[1])

dx=abs(x1-x2)
dy=abs(y1-y2)
if(x1==x2 and y1==y2) or checkerboard[x2][y2]==1:
  print("No")
elif (dx==2 and dy==1) or(dx==1 and dy==2):
  print("Yes")
else:
  print("No")

position1=input().split()
x1,y1=int(position1[0]),int(position1[1])
position2=input().split()
x2,y2=int(position2[0]),int(position2[1])
if x1==x2 and y1==y2:
  print("No")
elif checkerboard[x2][y2]==1:
  print("No")
else:
  if y1==y2 and x2-x1==1:
    print("Yes")
  else:
    print("No")

position1=input().split()
position2=input().split()
x1,y1=int(position1[0]),int(position1[1])
x2,y2=int(position2[0]),int(position2[1])
if checkerboard[x2][y2]==1:
  print("No")
elif (x1==x2 and y1==y2) or (abs(x2-x1)!=abs(y2-y1) and x1!=x2 and y1!=y2):
  print("No")
else:
  dx=(x2-x1)//max(1, abs(x2-x1))
  dy=(y2-y1)//max(1, abs(y2-y1))
  cx,cy=x1+dx, y1+dy
  reachable=True
  while cx!=x2 or cy!=y2:
    if checkerboard[cx][cy]==1:
      reachable=False
      break
    cx+=dx
    cy+=dy
  if reachable:
    print("Yes")
  else:
    print("No")

position1=input().split()
position2=input().split()
x1,y1=int(position1[0]),int(position1[1])
x2,y2=int(position2[0]),int(position2[1])

if x1==x2 and y1==y2:
	print("No")
elif checkerboard[x2][y2]==1:
	print("No")
else:
	if abs(x1-x2)<=1 and abs(y1-y2)<=1:
		print("Yes")
	else:
		print("No")

position1=input().split()
position2=input().split()
x1,y1=int(position1[0]),int(position1[1])
x2,y2=int(position2[0]),int(position2[1])

position1=input().split()
x1,y1=int(position1[0]),int(position1[1])
position2=input().split()
x2,y2=int(position2[0]),int(position2[1])
if x1==x2 and y1==y2:
  print("No")
elif checkerboard[x2][y2]==1:
  print("No")
else:
  if y1==y2 and x2-x1==1:
    print("Yes")
  else:
    print("No")

position1=input().split()
position2=input().split()
x1,y1=int(position1[0]),int(position1[1])
x2,y2=int(position2[0]),int(position2[1])

dx=abs(x1-x2)
dy=abs(y1-y2)
if(x1==x2 and y1==y2) or checkerboard[x2][y2]==1:
  print("No")
elif (dx==2 and dy==1) or(dx==1 and dy==2):
  print("Yes")
else:
  print("No")